/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blue_made_bluegin_Uniforms */

#ifndef _Included_blue_made_bluegin_Uniforms
#define _Included_blue_made_bluegin_Uniforms
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     blue_made_bluegin_Uniforms
 * Method:    native_init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_blue_made_bluegin_Uniforms_native_1init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blue_made_bluegin_Uniforms
 * Method:    native_data
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_blue_made_bluegin_Uniforms_native_1data
  (JNIEnv *, jclass, jlong, jstring, jstring, jobject);

/*
 * Class:     blue_made_bluegin_Uniforms
 * Method:    native_remove
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_blue_made_bluegin_Uniforms_native_1remove
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     blue_made_bluegin_Uniforms
 * Method:    native_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_blue_made_bluegin_Uniforms_native_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
